#!/usr/bin/env python
"""Write a sourceable env profile for one index + query set.

The harness is configured entirely by `BM25_TUNE_*` environment variables, and
on a new corpus **seven** of them move together. Typing them by hand once per
shell is where the two silent failures live:

- **A forgotten `BM25_TUNE_DATA_DIR`** points the run at the ClimbMix data dir,
  whose `judgments/` cache is keyed `prompt::topic_id::chunk_id` with *no corpus
  component*. A topic id collision then serves ClimbMix grades for the new
  corpus's passages — a complete, plausible, wrong score matrix.
- **A forgotten `BM25_TUNE_EXPECTED_NUM_DOCS`** leaves the index-identity guard
  pinned to ClimbMix's 921,892,634 chunks, so the new index refuses to open —
  the loud failure — or, if disabled, no longer notices a rebuild.

So the profile is generated, once, from the index itself: `num_docs` is read off
the live index rather than typed, which is the whole reason this is a script and
not a documented template.

`BM25_TUNE_BUDGET_USD` is deliberately written as a **commented-out** line. It is
the one variable with no default anywhere in the code (PLAN §0) — the spend
ceiling must be a live decision by whoever launches a spending command, not a
value they inherited from a file they generated last week and no longer read.

Usage:

    export JAVA_HOME="$PWD/tasks/bm25_tune/env/lib/jvm"
    uv run --project tasks/bm25_tune python \\
        skills/bm25-parameter-tuning/scripts/make_profile.py \\
        --name mycorpus --index /path/to/lucene-index \\
        --out /tmp/mycorpus.env
    source /tmp/mycorpus.env

Exit codes: 0 = written, 1 = the index could not be opened or read, 2 = the
output file exists and `--force` was not given.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# scripts/ -> bm25-parameter-tuning/ -> skills/ -> repo root.
REPO_ROOT = Path(__file__).resolve().parents[3]
TASK_ROOT = REPO_ROOT / "tasks" / "bm25_tune"

EXIT_OK = 0
EXIT_INDEX_UNUSABLE = 1
EXIT_EXISTS = 2


def _num_docs(index_dir: Path) -> int:
    """Open the index and read its document count, or raise `RuntimeError`.

    Kept separate from the rendering so the failure message can name the JDK/env
    requirement — the overwhelmingly likely cause of an import error here — rather
    than surfacing a pyserini traceback.
    """
    # Checked before opening: pyserini's own failure here is a 20-line Java
    # stack trace for what is almost always a typo in the path.
    if not index_dir.is_dir():
        raise RuntimeError(f"not a directory: {index_dir}")
    sys.path.insert(0, str(TASK_ROOT))
    try:
        from pyserini.search.lucene import LuceneSearcher
    except Exception as exc:  # noqa: BLE001 - any import failure is the same advice
        raise RuntimeError(
            "could not import pyserini.search.lucene. Run this under the task "
            "env with JDK 21 on JAVA_HOME:\n"
            '  export JAVA_HOME="$PWD/tasks/bm25_tune/env/lib/jvm"\n'
            "  uv run --project tasks/bm25_tune python "
            f"{Path(__file__).name} ...\n({type(exc).__name__}: {exc})") from exc
    try:
        searcher = LuceneSearcher(str(index_dir))
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError(
            f"failed to open {index_dir}: {type(exc).__name__}: {exc}") from exc
    count = int(getattr(searcher, "num_docs", -1))
    if count <= 0:
        raise RuntimeError(
            f"{index_dir} opened but reports num_docs={count} — an empty index "
            "has nothing to tune on")
    return count


def render(name: str, index_dir: Path, num_docs: int, data_dir: Path,
           grid_k1: str, grid_b: str, baseline: str, queries_full: str,
           queries_subsample: str, judge_model: str | None,
           judge_region: str | None, concurrency: int | None) -> str:
    """The profile text. Pure, so the wording is reviewable without an index."""
    lines = [
        f"# BM25 tuning profile: {name}",
        f"# Generated by {Path(__file__).name} against {index_dir}.",
        "# `source` this file, then run the pipeline from the repo root.",
        "",
        "# JDK 21 — pyserini needs it, and so does the test suite.",
        f'export JAVA_HOME="{REPO_ROOT}/tasks/bm25_tune/env/lib/jvm"',
        "",
        "# --- the corpus -------------------------------------------------",
        f'export BM25_TUNE_INDEX_DIR="{index_dir}"',
        "# Read off the live index, not typed. The guard is what makes a cached",
        "# judgment safe to reuse: a rebuilt or re-chunked index under this same",
        "# path would score new passages against grades given to old ones.",
        f"export BM25_TUNE_EXPECTED_NUM_DOCS={num_docs}",
        "",
        "# --- where judgments and runs accumulate ------------------------",
        "# Per corpus, ALWAYS. The judgment cache key is",
        "# prompt_version::topic_id::chunk_id with no corpus component, so two",
        "# corpora sharing a data dir can serve each other's grades wherever a",
        "# topic id collides.",
        f'export BM25_TUNE_DATA_DIR="{data_dir}"',
        "",
        "# --- the experiment --------------------------------------------",
        f'export BM25_TUNE_GRID_K1="{grid_k1}"',
        f'export BM25_TUNE_GRID_B="{grid_b}"',
        f'export BM25_TUNE_BASELINE="{baseline}"',
        f'export BM25_TUNE_QUERIES_FULL="{queries_full}"',
        f'export BM25_TUNE_QUERIES_SUBSAMPLE="{queries_subsample}"',
    ]
    if judge_model or judge_region or concurrency is not None:
        lines += ["", "# --- the judge --------------------------------------------------"]
        if judge_model:
            lines.append(f'export BM25_TUNE_JUDGE_MODEL="{judge_model}"')
        if judge_region:
            lines.append(f'export BM25_TUNE_JUDGE_REGION="{judge_region}"')
        if concurrency is not None:
            lines.append(f"export BM25_TUNE_JUDGE_CONCURRENCY={concurrency}")
    lines += [
        "",
        "# --- the spend ceiling: NOT set here, on purpose ----------------",
        "# This variable has no default anywhere in the code. Export it in the",
        "# shell that launches a spending command, so the ceiling is a decision",
        "# someone is making now rather than one inherited from this file.",
        "#   export BM25_TUNE_BUDGET_USD=50.0",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--name", required=True,
                        help="short corpus name; used in the header and in the "
                             "default data dir")
    parser.add_argument("--index", required=True, type=Path,
                        help="the Anserini/Lucene index directory")
    parser.add_argument("--out", type=Path, default=None,
                        help="write here instead of stdout")
    parser.add_argument("--force", action="store_true",
                        help="overwrite an existing --out")
    parser.add_argument("--data-dir", type=Path, default=None,
                        help="BM25_TUNE_DATA_DIR (default: "
                             "data/bm25-tune-<name> under the repo — under "
                             "data/, never under tasks/)")
    parser.add_argument("--grid-k1", default="0.5,0.7,0.9,1.2,1.6",
                        help="BM25_TUNE_GRID_K1 (default: the plan's 5 values)")
    parser.add_argument("--grid-b", default="0.2,0.35,0.5,0.65,0.8",
                        help="BM25_TUNE_GRID_B (default: the plan's 5 values)")
    parser.add_argument("--baseline", default="0.9:0.4",
                        help="the cell every candidate is compared to; "
                             "pyserini's default is 0.9:0.4, Lucene's is "
                             "1.2:0.75 (default: 0.9:0.4)")
    parser.add_argument("--queries-full", default=None, metavar="BASENAME",
                        help="BM25_TUNE_QUERIES_FULL (default: "
                             "<name>-queries.jsonl — a name carrying the "
                             "corpus, since keyword-1063.jsonl would be a lie "
                             "in every log line)")
    parser.add_argument("--queries-subsample", default=None, metavar="BASENAME",
                        help="BM25_TUNE_QUERIES_SUBSAMPLE (default: "
                             "<name>-subsample.jsonl)")
    parser.add_argument("--judge-model", default=None,
                        help="BM25_TUNE_JUDGE_MODEL (omit to keep the default)")
    parser.add_argument("--judge-region", default=None,
                        help="BM25_TUNE_JUDGE_REGION (omit to keep the default)")
    parser.add_argument("--concurrency", type=int, default=None,
                        help="BM25_TUNE_JUDGE_CONCURRENCY (omit to keep 16)")
    args = parser.parse_args(argv)

    if args.out is not None and args.out.exists() and not args.force:
        print(f"{args.out} exists — pass --force to overwrite", file=sys.stderr)
        return EXIT_EXISTS

    index_dir = args.index.expanduser().resolve()
    try:
        num_docs = _num_docs(index_dir)
    except RuntimeError as exc:
        print(str(exc), file=sys.stderr)
        return EXIT_INDEX_UNUSABLE

    data_dir = (args.data_dir.expanduser().resolve() if args.data_dir
                else REPO_ROOT / "data" / f"bm25-tune-{args.name}")
    text = render(
        name=args.name, index_dir=index_dir, num_docs=num_docs,
        data_dir=data_dir, grid_k1=args.grid_k1, grid_b=args.grid_b,
        baseline=args.baseline,
        queries_full=args.queries_full or f"{args.name}-queries.jsonl",
        queries_subsample=(args.queries_subsample
                           or f"{args.name}-subsample.jsonl"),
        judge_model=args.judge_model, judge_region=args.judge_region,
        concurrency=args.concurrency)

    if args.out is None:
        sys.stdout.write(text)
    else:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text, encoding="utf-8")
        print(f"wrote {args.out} (num_docs={num_docs})\n\nsource {args.out}",
              file=sys.stderr)
    return EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
